---
- name: Add i386 architecture
  command: dpkg --add-architecture i386
  tags:
    - arch
    - install
    - packages

- name: Install common packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - bc
    - build-essential
    - ccache
    - cron
    - curl
    - distcc
    - distcc-pump
    - git-core
    - htop
    - libelf-dev
    - libgcc1:i386
    - libncurses5:i386
    - libisl15
    - libisl15:i386
    - libssl-dev
    - libstdc++6:i386
    - lzop
    - msmtp
    - python
    - python-keyring
    - python-pyelftools
    - python-requests
    - u-boot-tools
    - unzip
    - zlib1g:i386
  tags:
    - install
    - packages

- name: Install packages for Debian Jessie
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "jessie"
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - gcc-4.9
    - gcc-4.9-plugin-dev
    - openjdk-7-jre-headless
  tags:
    - install
    - packages

- name: Install packages for Ubuntu and Debian Stretch
  when: (ansible_distribution == "Debian" and ansible_distribution_version == "stretch/sid") or
        (ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial")
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - gcc-5
    - gcc-5-plugin-dev
    - gcc-arm-linux-gnueabi
    - gcc-arm-linux-gnueabihf
    - openjdk-8-jre-headless
  tags:
    - install
    - packages
